# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('deadline', models.DateTimeField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('reminder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mycalendar.Reminder')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            bases=('mycalendar.reminder',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('reminder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mycalendar.Reminder')),
                ('etc', models.DurationField()),
            ],
            bases=('mycalendar.reminder',),
        ),
    ]
